[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.2"
serde = "1.0.214"
tokio = { version = "1.41.1", features = ["full"] }
tower = "0.5.1"
tower-http = { version = "0.6.1", features = ["cors"] }
utoipa = "5.2.0"
utoipa-axum = "0.2.0"
